#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}

entry("fork");
entry("exit");
entry("wait");
entry("waitpid");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("lseek");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");
entry("sigalarm");
entry("sigreturn");
entry("symlink");
entry("mmap");
entry("munmap");
entry("backtrace");
entry("memsnapshot");
entry("vaquery");
entry("consolemode");
entry("sched_set_hint");
entry("sched_set_weight");
entry("sched_get_stats");
entry("schedtrace");
entry("ucontext_switch");
entry("setpgid");
entry("getpgid");
entry("procctl");
entry("tcsetpgrp");
